# Generated by Django 2.1.7 on 2020-05-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='photo_two',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
    ]
