# Generated by Django 2.1.7 on 2020-05-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhp', '0002_document_photo_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='out_put',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='out_put_two',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
    ]
